dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh |
  bash
notifications:
  slack:
    secure: nYhk28LonteEBBvpGsdPwzEtMyXf2DU/Ly+1il0DVsOb4N4Z2tlEFBJYueRzg+VQ9IVVs93GVr8ki2HFTk/6npywb4ZyUXNXOo5XEXvgGfqiPb5AjhUM9+UQEJpGss4O+fzrizOn9izyrJHhP4iR82DaLCslCnCErbh5Zr2azZh6KwAoJioKV7PdXryBxQlGVWKlfenQfNpcvHzM/UIn460XCg6M53c5Gam3+NPj60c0JMpqSzU371GnfjJK9XyHCeHxkgf5YcqIXzIPWxNg+68Wtllx40UMMg1Szc+F9BYBgcppf27lbWN1bNlFc2XHqOosLcS85NORc3iAjaKzaxbYMzs5ilaljCHaRWccGgbPIdQGC2mrXGtI/cXsZIMUWYQOUkO80F3T9CiPzxAJIG/w/8/6pKhwRBjTePkbC+VpK2xPIDhHG/Gs1+d8Tfg84jiKBIa70MNojiswTsPm2XNXuokie8A4mY67vLBDPSJzSYHdUzUrwk0XTGhBqHHoJ8FfY/ENF+F/Ihir9JfJBd39CO47j/FFU0nKySQ8xJCI07CKL5zVYEerFIUyryG37w3IqHq6rYrCOfE0jIOHFC3h9Z2EpkqrLV5NBRnubABiDFw+nVzVCjFTJBHKxbfi2t91OJntm5y1GfwiQidvLas2KKs21yDRYnvCu9cpiLo=
