---
- hosts:all
  become: yes
  tasks:
    - name: Docker network
      docker_network:
        name: default

    - name: Run container
      docker_container:
        image: Chichavl/otus-reddit:1.0
        state: started
        restart_policy: always
        restart_policy_retry: 3
        networks:
          - default
        ports:
          - 0.0.0.0:9292:9292
      
