---
- hosts: all
  become: yes
  tasks:
  - name: Import key
    apt_key:
      keyserver: p80.pool.sks-keyservers.net
      id: 58118E89F3A912897C070ADBF76221572C52609D

  - name: Add docker repo
    apt_repository:
      repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
      state: present

  - name: Install docker package
    apt:
      name: docker-engine
      update_cache: yes

